apiVersion: v1
kind: Service
metadata:
  name: car-rental-app
spec:
  ports:
    - nodePort: 31290
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: car-rental-app
  type: NodePort
  