apiVersion: v1
kind: Service
metadata:
  labels:
    app: car-rental-app
  name: car-rental-app
spec:
  ports:
    - nodePort: 30955
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: car-rental-app
  type: LoadBalancer